config/routes.rb
# config/routes.rb
Rails.application.routes.draw do
  # ... other routes ...

  resources :customers, only: [:show, :index] do
    collection do
      get 'alphabetized'
      get 'missing_email'
    end
  end

  # If you have not defined the path names using `collection` block inside `resources`,
  # you can define them like this:
  get '/customers/alphabetized', to: 'customers#alphabetized', as: 'customers_alphabetized'
  get '/customers/missing_email', to: 'customers#missing_email', as: 'customers_missing_email'

  # ... other routes ...
end

app/models/application_record.rb
# app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/customer.rb
# app/models/customer.rb
class Customer < ApplicationRecord
  has_one_attached :image
  validates :full_name, presence: true
  validates :email_address, format: { with: URI::MailTo::EMAIL_REGEXP }, allow_blank: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/customers_controller.rb
# app/controllers/customers_controller.rb
class CustomersController < ApplicationController
  def show
    @customer = Customer.find(params[:id])
  end

  def index
    @customers = Customer.all
  end

  def alphabetized
    @customers = Customer.order(:full_name)
  end

  def missing_email
    @customers = Customer.where(email_address: [nil, ''])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/customers_helper.rb
module CustomersHelper
end

app/views/customers/_customer.html.erb
<!-- app/views/customers/_customer.html.erb -->
<div class="box">
  <article class="media">
    <div class="media-left">
      <%= image_tag customer.image, class: 'image-customer' if customer.image.attached? %>
    </div>
    <div class="media-content">
      <div class="content">
        <strong><%= customer.full_name %></strong>
        <br>
        Phone: <%= customer.phone_number %>
        <br>
        Email: <%= customer.email_address %>
        <br>
        Notes: <%= customer.notes %>
      </div>
    </div>
  </article>
</div>

app/views/customers/alphabetized.html.erb
<!-- app/views/customers/alphabetized.html.erb -->
<h1>Alphabetized NBA Customers</h1>
<%= link_to 'All Customers', customers_path %>
<%= link_to 'Customers Missing Email', customers_missing_email_path %>
<% @customers.each do |customer| %>
  <%= render 'customer', customer: customer %>
<% end %>

app/views/customers/index.html.erb
<!-- app/views/customers/index.html.erb -->
<h1>All The Customers</h1>
<%= link_to 'Alphabetized Customers', customers_alphabetized_path %>
<%= link_to 'Customers Missing Email', customers_missing_email_path %>
<% @customers.each do |customer| %>
  <%= render 'customer', customer: customer %>
<% end %>

app/views/customers/missing_email.html.erb
<!-- app/views/customers/missing_email.html.erb -->
<h1>The Customers Missing Email</h1>
<%= link_to 'All Customers', customers_path %>
<%= link_to 'Alphabetized Customers', customers_alphabetized_path %>
<% @customers.each do |customer| %>
  <%= render 'customer', customer: customer %>
<% end %>

app/views/customers/show.html.erb
<!-- app/views/customers/show.html.erb -->
<%= render 'customer', customer: @customer %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>U6Assignment</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>